[package]
name = "clear-or-close"
version = "0.1.0"
authors = ["Max Görner"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "~0.8.3"


[profile.release]
lto = true
